### ISSUE TITLE
Less: Escape sequences in idents

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#52]
Twitter's Bootstrap does the following a lot in its .less files.

```
padding-right: 4px \9;
```

I'm getting an error, No viable alternative at input '\', at every occurrence of this.

I also get a different error if the \9 is inside a string.

```
background-color: darken(@white, 15%) e("\9");
```

I get Illegal escape character \9. Are these not valid LESS?

**Comment by vtst** [comment]
Thanks for the bug report. I implemented the escape sequences in identifiers. This is in the code base, and will be available in the next release.

**Comment by mchiocca** [comment]
Hello. I pulled your changes, reran the run configuration that generates the parser classes, and rebuilt my workspace, but I'm still seeing the same errors. I get an Illegal escape character for strings such as "\9" and I get a No viable alternative to input '\' for things like \9.

**Comment by vtst** [comment]
I checked on my side, and I did'nt have any error with the following file:

``` css
.foo {
    @white: #FFF;
    padding-right: 4px \9;
    background-color: darken(@white, 15%) e("\9");
}
```

Can you try this example? I'll probably release a new version of the plugin today, you may give it a try.

**Comment by asins** [comment]
for IE9 css hack 

``` css
 background-color: red e("\9\0");
```

Parsed into

``` css
 background-color: red \9 \0;
```

But did not work properly, I want is `\9\0`, for more than a single space. what can I do？

**Comment by vtst** [comment]
I'm not sure to understand what your point is. It seems the plugin is working correctly there.

**Comment by ViRuSTriNiTy** [comment]
@asins You can write it this way: `background-color: e("red\9\0");`
