### ISSUE TITLE
Less: Escape sequences in strings.

### ISSUE THREAD

**Issue by mchiocca** [vtst/ow#55]
Consider this example

```
small {
    display: block;
    line-height: @baseLineHeight;
    color: @grayLight;
    &:before {
        content: '\2014 \00A0';
   }
}
```

I'm getting errors on the content property following by an EOF error on the closing curly brace.

```
Multiple markers at this line
- mismatched character '2' expecting set null
- no viable alternative at input '\'
- no viable alternative at input 'A0'
- mismatched character '<EOF>' expecting '''
```

**Comment by vtst** [comment]
Thanks for the bug report. I implemented the escape sequences in strings. This is in the code base, and will be available in the next release.

**Comment by mchiocca** [comment]
Hi. Even after pulling your changes and rebuilding I'm still seeing the same errors. For a string like '\2014 \00A0' I'm getting the following still.

```
Multiple markers at this line
- no viable alternative at input '\'
- mismatched character '2' expecting set null
- mismatched character '<EOF>' expecting '''
- no viable alternative at input 'A0'
```

**Comment by vtst** [comment]
Again, I have no problem on my side. Let's check with the released version.
After re-strarting Eclipse, did you make a modification in the LESS file so that the plugin parses it again?

**Comment by mchiocca** [comment]
That was it. I triggered a rebuild of my workspace. After that, the error markings for the escape sequences disappeared. Thanks!
