### ISSUE TITLE
JS: Project folder not handled correctly in source input path.

### ISSUE THREAD

**Issue by firecow** [vtst/ow#56]
Hi, tried the new version on both a Mac and my Ubuntu machine...

I've tried with a simple test project, in a clean new workspace, with one JS file, one goog.provide and i can't get code completion working..
Even installed my eclipse from stratch. Made sure all hidden eclipse setting files were deleted etc. etc..

Here is my setup. I'm in the Javascript Perspective.

Preferences -> Javascript -> Closure -> Closure base directory "/home/me/app/closure-library-read-only/closure/goog"
Preferences -> Javascript -> Editor -> Content Assist -> Advanced -> "Unflagged all but Closure Completion Proposals"
Project -> Properties -> Enable support for Closure Library and Closure Compiler

It simply doesn't build.
Under Project -> Properties -> Builders -> "Closure Javascript Builder is flagged"

I don't quite understand, what i'm doing wrong.
Can you see any errors in my Eclipse setup ?

**Comment by vtst** [comment]
Your configuration seems ok to me. You should check that /home/me/app/closure-library-read-only/closure/goog contains base.js.
The current version of the plugin outputs some debug message on the standard output. So you should start Eclipse from a terminal, and have a look to what is output there.

**Comment by SeanCoder** [comment]
I am experiencing exactly the same problem on Windows 7 and my folder contains both base.js and deps.js.

I used folder "D:\Projects\Libraries\Closure\closure-library\trunk\closure\goog" and the plugin it would not create the related '*.ow' files. I did find that after setting the location to "D:\Projects\Libraries\Closure\closure-library\trunk" the plugin did create these files but content assist still does not work, even after I changed it back to "D:\Projects\Libraries\Closure\closure-library\trunk\closure\goog" it still would not work.

I am working on Windows 7 with latest Eclipse Indigo (Java EE) version.

**Comment by firecow** [comment]
"/home/me/app/closure-library-read-only/closure/goog" does contain base.js, deps.js and all the other closure library folders.
Just like SeanCoder the js.ow files have been constructed, and looking inside one of the js.ow files, all the functions are there with the code stripped out.

-- Terminal Debug --
Initializing builder for: TestExample
Start build: TestExample
Computing project order
Updating referenced projects of: TestExample

Each time i change some code in one of the testexample js files, another build is issues, and i get the following in the terminal.
-- Terminal --
Start build: TestExample
End build: TestExample

But still code completion isn't working..

**Comment by vtst** [comment]
Hi,

I think I found the problem. A bug was introduced in version 0.2.2 with the new feature which allows specifying in which folders the JS source files are located. If you put the JS source files at the root of the project, it does not work. If you put them in a sub-directory, and add this directory in the project properties (page JavaScript > Include Path > Source), it works.

I'll fix the bug this week-end, sorry for the inconvenience.

## 

Vincent

**Comment by firecow** [comment]
You are right, that worked :D
I'll include them there for now, until its fixed...

**Comment by vtst** [comment]
Version 0.2.3 released fix the bug fix.

**Comment by SeanCoder** [comment]
Thanks for the update but I am afraid even with this update the plugin does not work correctly on my Windows 7 box. Permissions on the folder has been set correctly so that should not be a problem.

The ow files are not generated when I specify the root directory that contains base.js. I still have to specify one directory up before it creates those files.

Content Assist does not work in any situation whether I specify the root directory or one up. I also moved my code to a sub directory in my project and that did not work either.

I will try to test the same eclipse version on my ubuntu and mac systems to see if it works there.

**Comment by vtst** [comment]
There might be a Windows specific issue. Nevertheless, I just noticed I made a mistake while generating version 0.2.3, so I released a version 0.2.4 just after. You should check which version you have, sorry.

**Comment by SeanCoder** [comment]
No problem: I just updated to the latest version and it still does not work on Windows.

I installed the exact same environment on my mac and it works perfectly on the Mac, great job by the way, makes it so much easier to traverse all the Closure packages\classes and I am looking forward to using the Soy template plugin too.

You are correct and It looks like this is a Windows only problem.

**Comment by SeanCoder** [comment]
Quick update: I downloaded your source code and after running the mwe2 files I debugged the plugins within eclipse on windows 7 and that worked perfectly and content assist works just fine.

I am not yet sure why this is the case but it might be working because I built it on Windows, grabbing at straws :-)

**Comment by SeanCoder** [comment]
Hi vtst I was able to get the plugin to work by recreating my workspace from scratch and I have no problems with the latest version any more. It was odd that it worked fine with the debug version but at least I can now work with the released code.

**Comment by vtst** [comment]
Glad to hear it now works! Thanks for the feedback.
