### ISSUE TITLE
JS: Options for handling large projects

### ISSUE THREAD

**Issue by vtst** [vtst/ow#98]
Several users have reported memory issues when managing large JS projects with the Closure plugin.
Add two options for coping with that:
1. Analyzing only opened JS files,
2. Caching compilation results only for opened JS files.

**Comment by mattadamson** [comment]
Hi

We're also getting a similar issue with a very large project. Does the update above mean this could be fixed? If so how can we update eclipse to use this latest update? The only published version is 0.2.7.0. 

Thanks

Matt

**Comment by vtst** [comment]
This is fixed and the codebase, and will be available in the next release.

**Comment by mattadamson** [comment]
Thanks however how can I obtain the fix if not through the eclipse site as this only has 0.2.7.0?

Date: Wed, 24 Oct 2012 11:40:25 -0700

**Comment by vtst** [comment]
The fix is released as part of the version 0.2.8 of the plugin.

**Comment by mattadamson** [comment]
Thanks however we are still having issues using a large project. Can you think of anything else we can try?

Date: Sat, 27 Oct 2012 02:37:27 -0700
